//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTernarySearchTree
{
    using System;
    using System.Collections.Generic;
    
    public partial class Essay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Essay()
        {
            this.Histories = new HashSet<History>();
            this.Notes = new HashSet<Note>();
        }
    
        public string Id { get; set; }
        public string Text { get; set; }
        public string Topic { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime theLastFixingTime { get; set; }
        public bool isDeleted { get; set; }
        public string userId { get; set; }
        public string historyId { get; set; }
        public bool isPublish { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
    }
}
