//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTernarySearchTree
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public string id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string userId { get; set; }
        public string essayId { get; set; }
        public string oldEssay { get; set; }
        public string newEssay { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Essay Essay { get; set; }
    }
}
