//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTernarySearchTree
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NotesId { get; set; }
        public string Sentence { get; set; }
        public string Mean { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public string EssayId { get; set; }
    
        public virtual Essay Essay { get; set; }
    }
}
