//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTernarySearchTree
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phonetic
    {
        public string phoneticId { get; set; }
        public string text { get; set; }
        public string audio { get; set; }
        public string wordId { get; set; }
    
        public virtual Word Word { get; set; }
    }
}
